extraction:
  cpp:
    prepare:
      packages:
        - libncurses-dev
    configure:
      command:
        - mkdir _lgtm_build_dir
        - cd _lgtm_build_dir
        - cmake ..
    index:
      build_command:
        - cd _lgtm_build_dir
        - make
