[platformio]
default_envs = BUILD_FOR_TEENSY4_1
src_dir = .

[env:BUILD_FOR_TEENSY4_1]
lib_ldf_mode = deep+
src_filter = +<*> -<.git/> -<.svn/> -<example/> -<examples/> -<test/> -<tests/> -<build> -<player.cpp>
lib_deps = bblanchon/ArduinoJson
	adafruit/Adafruit NeoPixel
	https://github.com/tsandmann/freertos-teensy.git
	https://github.com/PaulStoffregen/SD.git#c7cae3caeb3a596614add9d4174e5efbe5c1af56
	https://github.com/PaulStoffregen/SdFat.git#bc39d275f0576ea9fcc496342385115fc53cd282
	https://github.com/PaulStoffregen/SPI.git#574ab8c7a8a45ea21cc56dcc6b7361da90868e86
	https://github.com/folkertvanheusden/QNEthernet.git#266ee33b48e3f16502921234bf8a19ad412051ac
	https://github.com/luni64/TeensyTimerTool
extra_scripts = pre:prepare.py
platform = https://github.com/tsandmann/platform-teensy.git
board = teensy41
framework = arduino
build_flags = -Wformat=1 -DTEENSY_OPT_FASTER_LTO -DTEENSY4_1=1 -DFREERTOS=1 -fexceptions -DQNETHERNET_ENABLE_RAW_FRAME_SUPPORT=1 -DQNETHERNET_ENABLE_PROMISCUOUS_MODE=1 -DNEOPIXELS_PIN=18 -Wl,-Map,firmware.map -DLOAD_GAUGE_PIN=5 ; -DUSE_ARDUINO_DEFINES
upload_flags = -v
upload_protocol = teensy-cli
