[platformio]
default_envs = BUILD_FOR_PICO2W
src_dir = .

[env:BUILD_FOR_PICOW]
lib_ldf_mode = deep+
src_filter = +<*> -<.git/> -<.svn/> -<example/> -<examples/> -<test/> -<tests/> -<build> -<player.cpp>
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
#board = rpipico2w
board = rpipicow
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.2m
lib_deps = bblanchon/ArduinoJson
	greiman/SdFat
	adafruit/Adafruit NeoPixel@^1.10.4
build_flags = -Ofast -DBUILD_FOR_PICO2W=1 -DPIO_FRAMEWORK_ARDUINO_ENABLE_EXCEPTIONS -DPICO_STDIO_USB=1 -DDEBUG_PICO2W_PORT=Serial -DPIO_FRAMEWORK_ARDUINO_ENABLE_FREERTOS -DFREERTOS
build_unflags = -Os
extra_scripts = pre:prepare.py

[env:BUILD_FOR_PICO2W]
lib_ldf_mode = deep+
src_filter = +<*> -<.git/> -<.svn/> -<example/> -<examples/> -<test/> -<tests/> -<build> -<player.cpp>
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.2m
lib_deps = bblanchon/ArduinoJson
	greiman/SdFat
	adafruit/Adafruit NeoPixel@^1.10.4
build_flags = -Ofast -DBUILD_FOR_PICO2W=1 -DPIO_FRAMEWORK_ARDUINO_ENABLE_EXCEPTIONS -DPICO_STDIO_USB=1 -DDEBUG_PICO2W_PORT=Serial -DPIO_FRAMEWORK_ARDUINO_ENABLE_FREERTOS -DFREERTOS
build_unflags = -Os
extra_scripts = pre:prepare.py
